export const usuariosIniciais = [
  {
    nome: "João da Silva",
    cidade: "Recife",
    bairro: "Boa Viagem",
    email: "joao.silva@email.com",
    cpf: "123.456.789-10",
    password: "senha123",
    senha: "senha123",
    confirmaSenha: "senha123",
  },
  {
    nome: "Maria Oliveira",
    cidade: "Olinda",
    bairro: "Casa Caiada",
    email: "maria.oliveira@email.com",
    cpf: "987.654.321-00",
    password: "outrasenha",
    senha: "outrasenha",
    confirmaSenha: "outrasenha",
  },
  {
    nome: "Pedro Santos",
    cidade: "Paulista",
    bairro: "Janga",
    email: "pedro.santos@email.com",
    cpf: "567.890.123-45",
    password: "minhasenha",
    senha: "minhasenha",
    confirmaSenha: "minhasenha",
  },
  {
    nome: "Ana Souza",
    cidade: "Recife",
    bairro: "Ipsep",
    email: "ana.souza@email.com",
    cpf: "234.567.890-12",
    password: "outrasenha2",
    senha: "outrasenha2",
    confirmaSenha: "outrasenha2",
  },
  {
    nome: "José Oliveira",
    cidade: "Jaboatão dos Guararapes",
    bairro: "Piedade",
    email: "jose.oliveira@email.com",
    cpf: "654.321.098-76",
    password: "senha1234",
    senha: "senha1234",
    confirmaSenha: "senha1234",
  },
  {
    nome: "Mariana Silva",
    cidade: "Recife",
    bairro: "Derby",
    email: "mariana.silva@email.com",
    cpf: "345.678.901-23",
    password: "novasenha",
    senha: "novasenha",
    confirmaSenha: "novasenha",
  },
  {
    nome: "Rafael Pereira",
    cidade: "Camaragibe",
    bairro: "Vila da Fábrica",
    email: "rafael.pereira@email.com",
    cpf: "876.543.210-98",
    password: "senha12345",
    senha: "senha12345",
    confirmaSenha: "senha12345",
  },
];

export const ocorrenciasIniciais = [
  {
    //"tipoOcorrencia": "Assalto",
    geolocalizacao: "-8.0476,-34.8770",
    cidade: "Recife",
    bairro: "Santo Amaro",
    descricao: "Um pedestre foi abordado e teve seus pertences roubados.",
    dataHoraOcorrencia: "12/02/2023",
    hora: "08:45",
    usuarioId: 43,
    categoriaId: 2,
  },
  {
    //"tipoOcorrencia": "Furto",
    geolocalizacao: "-8.0543,-34.8813",
    cidade: "Recife",
    bairro: "Santo Amaro",
    descricao: "Uma residência foi invadida e alguns objetos foram furtados.",
    dataHoraOcorrencia: "21/05/2023",
    hora: "15:20",
    usuarioId: 45,
    categoriaId: 28,
  },
  {
    //"tipoOcorrencia": "Homicídio",
    geolocalizacao: "-8.0406,-34.9432",
    cidade: "Recife",
    bairro: "Várzea",
    descricao:
      "Um tiroteio resultou em uma vítima fatal nas proximidades de um bar.",
    dataHoraOcorrencia: "03/08/2023",
    hora: "23:10",
    usuarioId: 47,
    categoriaId: 3,
  },
  {
    //"tipoOcorrencia": "Roubo",
    geolocalizacao: "-7.9872,-34.8390",
    cidade: "Olinda",
    bairro: "Casa Caiada",
    descricao:
      "Um estabelecimento comercial foi assaltado por indivíduos armados.",
    dataHoraOcorrencia: "18/09/2023",
    hora: "19:30",
    usuarioId: 43,
    categoriaId: 27,
  },
  {
    //"tipoOcorrencia": "Dano",
    geolocalizacao: "-8.0205,-34.9286",
    bairro: "Alto do Mandu",
    cidade: "Recife",
    descricao:
      "Um veículo teve os vidros quebrados em um estacionamento público.",
    dataHoraOcorrencia: "09/04/2023",
    hora: "13:40",
    usuarioId: 45,
    categoriaId: 6,
  },
  {
    //"tipoOcorrencia": "Furto",
    geolocalizacao: "-8.0422,-34.9363",
    bairro: "Iputinga",
    cidade: "Recife",
    descricao: "Um celular foi furtado em um ponto de ônibus movimentado.",
    dataHoraOcorrencia: "15/07/2023",
    hora: "11:15",
    usuarioId: 47,
    categoriaId: 28,
  },
  {
    //"tipoOcorrencia": "Assalto",
    geolocalizacao: "-8.0368,-34.9342",
    bairro: "Iputinga",
    cidade: "Recife",
    descricao:
      "Um grupo de pessoas foi assaltado em uma praça durante a noite.",
    dataHoraOcorrencia: "29/10/2023",
    hora: "20:50",
    usuarioId: 43,
    categoriaId: 2,
  },
  {
    //"tipoOcorrencia": "Homicídio",
    geolocalizacao: "-7.9895,-34.8390",
    cidade: "Olinda",
    bairro: "Casa Caiada",
    descricao:
      "Um crime violento resultou na morte de um jovem próximo a uma escola.",
    dataHoraOcorrencia: "05/11/2023",
    hora: "01:30",
    usuarioId: 45,
    categoriaId: 3,
  },
];
